### ISSUE TITLE
Artifacts.

### ISSUE THREAD

**Issue by GAZ082** [ojrac/opensimplex-go#1]
Hi there. i'm having these artifacts when rendering big 2D arrays (lets say, 180x180 and up).
Top right corner, whe white spots.

![map](https://user-images.githubusercontent.com/100194/38460097-b867f294-3a89-11e8-8bb0-d24a2a1a461b.png)

Do you happen to encounter these artifacts as well? I'm reducing the output of your lib to to float32.

Thanks.

**Comment by ojrac** [comment]
I spent some time looking into it, and I think it's a problem with mapping the OpenSimplex noise output onto a normalized range. Looking at the Java reference implementation, people are having similar trouble:

https://gist.github.com/KdotJPG/b1270127455a94ac5d19#gistcomment-2132420

I'm interested in adding an API that returns a normalized range in [0, 1], but it's going to take more research before I can say what the min/max range should be.

I'm guessing the white spots are where your samples are underflowing from 0 to 255ish.

**Comment by GAZ082** [comment]
Thank you for having a look. Looking forward any change. I'm fine for now as when i normalize the values the artifacts are gone.

**Comment by ojrac** [comment]
The latest release (v1.0.0) adds options for normalized nose in [0, 1). Call `NewNormalized(seed int64)` to try it out.
