### ISSUE TITLE
Normalizing output of Eval2 to [0, 1)

### ISSUE THREAD

**Issue by ahday** [ojrac/opensimplex-go#2]
In my own efforts to normalize the output of Eval2 to [0, 1), I've found the following constants work well:

```go
    func normalize(r float64) float64 {
        base := 0.864366441
        scale := 0.5784583670
        
        return (r + base) * scale
    }
```

I've run this formula over very large samples (dim = 30,000; n = 900,000,000) with several different seeds and it produces values of 0.0 up to ~ 0.999999999 without ever producing 1.0.

There is some discussion in #1 of artifacts when casting to sizes smaller than float64. When the result of the above formula is cast to float32, it's possible to get 1.0. This may be fine if you want float32s in the closed range [0, 1], but it's different from the float64 guarantee of [0, 1).

Various solutions suggest themselves. One approach might be to provide a special alternative function along the lines of `Eval2float32` that calls Eval2, checks if the normalized value is >= 1.0, and returns ~ 0.9999 if necessary. Similarly, something like `Eval2int(x, y float64, max int) int` might cap its result at max - 1.

I'm implementing some of this in my own fork, and would be interested to see other opinions, and whether a PR might be welcome.

**Comment by ojrac** [comment]
I like the sound of this -- adding an NormalizedEval{2,3,4} with your constants that returns float64 sounds like a good start. I don't have strong feelings about float32 versions, but it sounds like it might avoid some surprises to add it with the range checks.

I've been meaning to tag a 1.0.0 release to prepare for Go modules; getting a normalized API in before that would be great. A PR would be great if you can make one.

**Comment by ahday** [comment]
Sure, I can do that. What do you think about having the plain Eval2 function, etc, return the normalized value?

**Comment by ojrac** [comment]
Okay, interface conversion is in. I moved a lot of code around, to split it into internal, "vanilla" noise, and left room for extra stuff in opensimplex.go.

I also added `Noise32` and `func AsNoise32(Noise) Noise32` to wrap a 64-bit Noise.

**Comment by ahday** [comment]
Great, working on this now. Have a Norm(), Norm32, and NormInt() function written. Let me adjust them to the interface stuff and I'll post it.

**Comment by ojrac** [comment]
Thanks for the commit. Let me know if/whenever you'd like to hand this off. It looks like the remaining work is:

* Figure out the rough min/max range of `Eval3` and `Eval4` (maybe writing a benchmark at the same time?)
* Add `Eval3` and `Eval4` to `noiseNormalized` so it implements `Noise`
* Add a `NoiseInt` interface for `noiseNormalizedInt`
* Add `AsNormalized` and `AsNormalizedInt` functions to give public access to the new noises

**Comment by ahday** [comment]
I'm working on another commit that will supply the `Eval3` and `Eval4` functions and allow `noiseNormalized` and `noiseNormalized32` to fulfill `Noise` and `Noise32`. I've actually removed the int-related types for now -- I'm not 100% sure they'll end up being necessary. I'll do a little more testing on them and add them back if appropriate.

How to do the public access is totally up to you. It seems like a lot of clutter to add As...() functions for every combination of normalized/bit-size/fractal... etc. I can't think of anything better, though.

**Comment by ojrac** [comment]
Hopefully we can avoid every combination by having As...() Options you can combine; the unsolved problem is mixing AsNormalized and AsNoise32 without rounding up to 1.

**Comment by ojrac** [comment]
After thinking for a bit, I'm not optimistic about solving AsNormalized and AsNoise32. It probably makes the most sense to have New(seed), NewNormalized(seed), and matching float32 versions rather than try to make every permutation work. It's verbose, but the other option lets you ask for hard stuff (like normalizing fractal noise).

**Comment by ahday** [comment]
One alternative would be to add a `normalized bool` param to the `New...()` functions, which then return either a `noise` or `normNoise` object. `AsNoise32` can check the underlying type, and create either a `normNoise` or `normNoise32` accordingly. This doesn't fit as well, though, with any future noise types, like a fractal.

**Comment by ojrac** [comment]
PR #3 merged.
