### ISSUE TITLE
Normalized output is sometimes < 0 or >= 1

### ISSUE THREAD

**Issue by clayts** [ojrac/opensimplex-go#9]
I was getting some values outside [0,1) so I tried recalculating the normMinN and normScaleN constants. After sampling about 50 billion values from each type of noise I ended up with this, and thought it might be worth sharing.

```
normMin2   = 0.8659203878240322
normScale2 = 0.577420288914181
normMin3   = 0.9871048542519545
normScale3 = 0.506595297177236
normMin4   = 1.0040848236330158
normScale4 = 0.5007450643319374
```

**Comment by ojrac** [comment]
Thanks for sharing your results! I've updated the constants and put them in v1.0.2.
